[package]
name = "simulator"
version = "0.1.0"
edition = "2021"
resolver = "2"
description = "Simulator for the converter package"

[dependencies]
nannou = "0.17"
converter = { path = "../converter" }
