[package]
name = "converter"
version = "0.1.0"
edition = "2018"
resolver = "2"
author = "Virghileanu Teodor <@GaussianWonder>"
description = "CNC Converter"

[dependencies]
# argument parser
clap = { version = "3.0.0-beta.1", features = ["std", "color", "suggestions", "cargo", "derive", "wrap_help", "unicode"] }
# imageproc dependencies?
sdl2 = { version = "0.34.2", optional = true, default-features = false, features = ["bundled"] }
sdl2-sys = "0.34.2"
# imageproc
imageproc = { version = "0.22.0", features = ["display-window"] }
image = "0.23.14"

[features]
display-window = ["sdl2"]